name: Doxygen

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Doxygen
      run: |
        sudo apt install -y doxygen
        doxygen Doxygen